### PR TITLE
Implement DropView query in SQLPPGenerator

### PR DESCRIPTION
**Pull request by luochen01**
Implemented DropView query in SQLPPGenerator. This query is used to physically remove a view from AsterixDB.

A sample query looks like:
`drop dataset test if exists;`

### CODE REVIEW

**Comment by JavierJia** [comment]
I think @haochen07 can review this PR :-)

**Comment by haochen07** [comment]
Looks good to me!

**Comment by chenlica** [comment]
Just curious: how can we prevent external users from making such kind of requests?  Should we do the protection at the network layer>

**Comment by JavierJia** [comment]
It will be a web admin console that requiring some authentications for the purpose of the `register` and `deregister` in the future.

**Pull request merged**
