### PR TITLE
Reset button for Zoom and TimeSeries

### PR DESCRIPTION
**Pull request by starmon00**
PR for adding "Reset Zoom" and reposition "info" to properly place reset button and changing reset button on time series to link

@JavierJia 

#124

### CODE REVIEW

**Comment by JavierJia** [comment]
@starmon00 everytime when you finished one task in a branch, you should delete it, update the local master with remote one , and then checkout a new branch from the master. Then the previous already merged commit won't show up here, which makes our commit history much cleaner.

**Comment by starmon00** [comment]
I didn't realize I was working on master branch. I will be aware of that next time sorry!

**Comment by JavierJia** [comment]
looks very nice! you can go ahead and merge it when the tests are passed.
👍

**Comment by JavierJia** [comment]
@starmon00 you can go ahead and merge.

**Pull request merged**
