### PR TITLE
Front-end Testing

### PR DESCRIPTION
**Pull request by starmon00**
PR to add front-end testing

#25 

@JavierJia

### CODE REVIEW

**Comment by JavierJia** [comment]
old branch?

**Comment by JavierJia** [comment]
since the change is small, could you start a new branch to avoid messing up the commit history? thanks.

**Comment by starmon00** [comment]
oh shoot, it went on old branch. I'll change

**Comment by starmon00** [comment]
So I think my master branch got contaminated with a history so it's permanently there. Would the solution be to create a new fork?

**Comment by JavierJia** [comment]
not new fork. "master" branch is just a name. you can delete that contaminated branch if you don't want it anymore. otherwise, you can rename it if you want to keep it. 

Then check out your clean "master" from the isg master. and then checkout a new branch from it.

**Comment by starmon00** [comment]
Closing due to using wrong branch.

**Pull request closed without merging**
