### PR TITLE
[Graph-Viz]Add a map in mapboxgl to the front-end

### PR DESCRIPTION
**Pull request by vichgy**
Add a map as the background of the interface.

### CODE REVIEW

**Comment by chenlica** [comment]
For public shared js libraries, do we need to include them in our repo or we can just cite them via a URL?

Also the subject of this PR needs to be more informative.  @sadeemsaleh please provide the guidance to @vichgy

**Comment by vichgy** [comment]
The original public shared js libraries, there are already files like deckgl.js and mapboxgl.min.js. Because the demo I followed used another version of deckgl and mapbox so that I just update the content in the file. We can also just import the js file from the URL. Which way do we prefer?

**Comment by chenlica** [comment]
Can we have a URL with the version number to make it stable?

In the subject of the PR, please add [Graph-Viz] as a prefix.

**Comment by vichgy** [comment]
So maybe we can add the URL and the version as a comment?

**Comment by chenlica** [comment]
We don't want to include external libraries unnecessarily.  Can you find a permanent URL with a right version?

**Comment by sadeemsaleh** [comment]
conflicts resolved in #703

**Pull request closed without merging**
