### PR TITLE
[issue #157] [WIP] Provide a point-view for the geo-location tagged Tweets

### PR DESCRIPTION
**Pull request by HotLemonJuice**
Issue #157 

Purpose:
- Plot the tweets by it's geolocation as a point.
screen shot 2017-03-06 at 16 41 41

Possible Implementation:
- the geocell function of the new data model.

### CODE REVIEW

**Comment by HotLemonJuice** [comment]
I have written a python script to generate test 200 test data based on one of the tweet data.
The format looks like this:
`{ "create_at": datetime("2015-11-23T16:14:03.000Z"), "id": 668945640186101761, "text": "Just posted a photo @ Campus Martius Park https://t.co/5Ax4E2CdWZ", "in_reply_to_status": -1, "in_reply_to_user": -1, "favorite_count": 0, "coordinate": point("-83.04647491,42.33170228"), "retweet_count": 0, "lang": "en", "is_retweet": false, "user": { "id": 48121888, "name": "Kevin McKague", "screen_name": "KevinOfMI", "lang": "en", "location": "Davison, Michigan", "create_at": date("2009-06-17"), "description": "I need to ride my bike until my brain shuts up and my muscles are screaming. \nRight after these donuts. Dad of 3.\n Visit my blog 18 Wheels and a 12-Speed Bike.", "followers_count": 1178, "friends_count": 1780, "statues_count": 22263 }, "place": { "country": "United States", "country_code": "United States", "full_name": "Detroit, MI", "id": "b463d3bd6064861b", "name": "Detroit", "place_type": "city", "bounding_box": rectangle("-82.592458,42.950683 -82.214922,43.146086") }, "geo_tag": { "stateID": 26, "stateName": "Michigan", "countyID": 26163, "countyName": "Wayne", "cityID": 2622000, "cityName": "Detroit" } }`

The only difference among all these 200 test data is the value `rectangle("-82.592458,42.950683 -82.214922,43.146086")` where all four numbers are incremented by a random number in the range of [-1, 1].

**Comment by JavierJia** [comment]
cool. a good start point!

**Comment by HotLemonJuice** [comment]
I have added these test data into the sample.adm and gzip it into a new sample.adm.gz. And I ran `./script/ingestTwitterToLocalCluster.sh` afterwards. Is this the correct way to ingest the data?

**Comment by JavierJia** [comment]
Yes. that should work. Why just 200 points? you could make more, right?

**Comment by JavierJia** [comment]
will it be better to give each record a `point` by randomize on its own `place. bounding_box.[0]` ?

**Comment by HotLemonJuice** [comment]
> will it be better to give each record a point by randomize on its own place. bounding_box.[0] ?

@JavierJia Do you mean go through each record from like 4 millions of records to give each of them a randomized point value?

**Comment by JavierJia** [comment]
yes. it might be helpful for you to test.

**Comment by HotLemonJuice** [comment]
And do you mean to insert a new `point` attribute under `place.bouding_box` using `place.bouding_box.rectangle[0]`?

**Comment by JavierJia** [comment]
nono, also no for the previous answer. I take it back. sorry 😢 

The no-precise-location problem will still exist because we are not gonna re-ingest the huge data again. 

A more appropriate solution could be as following: 

If the record has the `coordinate` field, e.g. `"coordinate": point("-83.04647491,42.33170228")`, that is the exact point provided by Twitter which we can directly show on the map. 

If it doesn't have one, we can use it's `place. bounding_box` information to create one. It's better to randomize it around the center instead of the `place. bounding_box[0]`. 

If it doesn't even have the `place.bounding_box`, which could be possible, we just  don't show it.

**Comment by HotLemonJuice** [comment]
So for each existing record, we will use `point` if it exists or simulate a `point` based on the center of its `bounding_box` if the `point` attribute doesn't exist, right?
So then we don't need to generate test data any more right?

**Comment by JavierJia** [comment]
correct 😀

**Comment by chenlica** [comment]
👍  My understanding is that we first show points at the city level, as a good starting point.

**Comment by HotLemonJuice** [comment]
I'm now working on displaying dots using some test point data on the map. I'm looking into the leaflet framework to make it work. 

I see that now the front-end only receives count results from the middleware. My assumption is that in the future the front-end will receive an array of point data.

**Comment by JavierJia** [comment]
yes, sure. by reading our [documentation](http://cloudberry.ics.uci.edu/documentation/), can you work out the required JSON request to the cloudberry?

**Comment by HotLemonJuice** [comment]
```
Data Schema: 
{
  "name":"twitter.ds_tweet",
  "schema":{"typeName":"twitter.typeTweet",
    "dimension":[
      {"name":"create_at","isOptional":false,"datatype":"Time"},
      {"name":"id","isOptional":false,"datatype":"Number"},
      {"name":"coordinate","isOptional":false,"datatype":"Point"},
      {"name":"lang","isOptional":false,"datatype":"String"},
      {"name":"hashtags","isOptional":true,"datatype":"Bag","innerType":"String"},
      {"name":"geo_tag.stateID","isOptional":false,"datatype":"Number"},
      {"name":"geo_tag.countyID","isOptional":false,"datatype":"Number"},
      {"name":"geo_tag.cityID","isOptional":false,"datatype":"Number"},
      {"name":"geo","isOptional":false,"datatype":"Hierarchy","innerType":"Number",
        "levels":[
          {"level":"state","field":"geo_tag.stateID"},
          {"level":"county","field":"geo_tag.countyID"},
          {"level":"city","field":"geo_tag.cityID"}]},
      {"name": "place.bounding_box", "isOptional":false,"datatype":"rectangle"}  //my change - But I notice the middleware doesn't have this rectangle datatype. Do we have to create this new datatype?
    ],
    "measurement":[
      {"name":"text","isOptional":false,"datatype":"Text"},
      {"name":"favorite_count","isOptional":false,"datatype":"Number"},
      {"name":"retweet_count","isOptional":false,"datatype":"Number"}
    ],
    "primaryKey":["id"],
    "timeField":"create_at"
  }
}

Query:
{
  "dataset": "twitter.ds_tweet",
  "filter": [
    {
      "field": "create_at",
      "relation": "inRange",
      "values": [ "2016-01-01T00:00:00.000Z", "2016-12-31T00:00:00.000Z"]
    },
    {
      "field": "text",
      "relation": "contains",
      "values": [ "zika", "virus" ]
    }
  ],
  "group": {
     "by": [
        {
          "field": "coordinate",  //my change
          "as": "point"
        },
        {
            "field": "place.bounding_box",   //my change
            "as": "rectangle"
        },
        {
          "field": "create_at",
          "apply": {
            "name": "interval",
            "args": {
              "unit": "hour"
            }
          },
          "as": "hour"
        }
      ]    //my change - I deleted aggregation here as it doesn't make sense to aggregate the count on each point
  }
}
```

**Comment by JavierJia** [comment]
As for `rectangle`, can we express it as a bag of `point`s? 
For the query part, we definitely don't need a `groupby`. Can you take a look at the current js code to see how the `sample` request looks like? (The `sample` request gets the actual tweet id and show it on the sidebar).

**Comment by HotLemonJuice** [comment]
I see. I think we can use the sample query to retrieve those point data. I added `"coordinate", "place.bounding_box"` in the `select.field`.
```
{
    "dataset":"twitter.ds_tweet",
    "filter":[
        {
            "field":"geo_tag.stateID",
            "relation":"in",
            "values":[37,51,24,11,10,34,42,9,44,48,35,4,40,6,20,32,8,49,12,22,28,1,13,45,5,47,21,29,54,17,18,39,19,55,26,27,31,56,41,46,16,30,53,38,25,36,50,33,23,2]
        },
        {
            "field":"create_at",
            "relation":"inRange",
            "values":["2017-03-14T18:57:07.994Z","2017-03-15T18:57:07.994Z"]
        },
        {
            "field":"text",
            "relation":"contains",
            "values":["bike"]
        }
    ],
    "select":{
        "order":["-create_at"],
        "limit":10,
        "offset":0,
        "field":["create_at","id","user.id", "coordinate", "place.bounding_box"] //myChange
    },
    "transform":{
        "wrap":{"key":"sample"}
    }
}
```

For the rectangle, it is essentially a bag of points, but can the middleware recognize it without some manual parsing since its format is like 
```
"bounding_box": rectangle("-124.482003,32.528832 -114.131212,42.009519")
``` 
but not 
```
"bounding_box": {
    point("-124.482003,32.528832"),
    point("-114.131212,42.009519")
}
```
?

**Comment by JavierJia** [comment]
hmm, it indeed a problem. the Rectangle is a special object we need to fully support in Cloudberry. Right now it's not implemented yet. But somehow it makes sense only in AsterixDB context and there is ongoing work to make it compatible with the `GeoJSON` format. We need to come up with a general enough "box" object. 

It will take time. Meanwhile, I think we have to reformat the data field of that `bounding_box` as an array of points?  e.g. [ point(133.0, 33), point(233,33] . 😭

**Comment by HotLemonJuice** [comment]
we can use city ID and coordinate to show the points first. No need to change the data for now.

**Pull request closed without merging**
