### PR TITLE
[issue#222]Cache along with replacement

### PR DESCRIPTION
**Pull request by vidhya567**
1. Added prefetch
2. Added Cache replacement
Step 1:When cache threshold is reached we find Target.
Step 2:Find the opposite corner in Cached Region based on request.
Step 3:Move towards current request till you reach target
Step 4:Delete the polygons from cache and insert the new polygons for the current request into the cache.

### CODE REVIEW

**Comment by JavierJia** [comment]
@waans11 Could you take a look at this PR? thanks!

**Comment by chenlica** [comment]
@vidhya567 To make it easier for other people to review your PR, please add a high-level description of your logic.  Also try to add a figure to explain the main idea.

Also the code needs comments.

**Comment by vidhya567** [comment]
@waans11  I am free on Monday and Tuesday.Say any time I will come on this days?

**Comment by waans11** [comment]
@vidhya567: Let's meet on Tuesday at 3:30 pm then.

**Comment by JavierJia** [comment]
We once use selenium-webdriver https://github.com/ISG-ICS/cloudberry/tree/master/neo/test/resources to test.

**Pull request closed without merging**
