### PR TITLE
fix New York geojson issue #71

### PR DESCRIPTION
**Pull request by xixZ**
@JavierJia

### CODE REVIEW

**Comment by JavierJia** [comment]
Could you add a simple test case that contains the "Manhattan" city in `noah/test/resource/sample.json` to verify that it is tagged correctly? Thanks!

**Comment by JavierJia** [comment]
@xixZ wanna add the test case and sync with the master 😄

**Comment by xixZ** [comment]
@JavierJia

**Comment by JavierJia** [comment]
The test failure is not relevant. Let me go ahead and merge it. Thanks @xixZ  and good luck to the internship!

**Pull request merged**
