### PR TITLE
Angular dc dashboard

### PR DESCRIPTION
**Pull request by JeremyLi28**

### CODE REVIEW

**Comment by JeremyLi28** [comment]
@JavierJia I'm not sure the above information is ok to merge: This branch is out-of-date with the base branch

**Comment by JavierJia** [comment]
correct, it not OK to merge this branch.  You should merge with `ISG-cloudberry` master not the master in your domain.

**Comment by JavierJia** [comment]
how to merge with upstream branch: https://help.github.com/articles/syncing-a-fork/

**Comment by JavierJia** [comment]
It looks fine. I think the problem is that we switch the master with play-angular

**Pull request merged**
