### PR TITLE
Video demo and cloudberry

### PR DESCRIPTION
**Pull request by vidhya567**
Add video and power by button

### CODE REVIEW

**Comment by JavierJia** [comment]
Please upload a screenshot (or two for different width ?) to let us know the effects. Thanks!

**Comment by vidhya567** [comment]
screen shot 2017-03-06 at 10 08 22 am
screen shot 2017-03-06 at 10 11 40 am

**Comment by vidhya567** [comment]
Can I merge?
screen shot 2017-03-06 at 10 14 45 am

**Comment by JavierJia** [comment]
Looks good! 👍

**Pull request merged**
