### PR TITLE
Publish Shengjie's report

### PR DESCRIPTION
**Pull request by HotLemonJuice**
This PR is for the publication of Shengjie Xu's report (development guide).

The report PDF file is put under /docs/img following the same rule with the `Cloudberry20170324.pptx` file.

### CODE REVIEW

**Comment by JavierJia** [comment]
LGTM 👍

**Comment by chenlica** [comment]
Please let me know when the new pub is on the web site.

**Comment by JavierJia** [comment]
just pushed. http://cloudberry.ics.uci.edu/pubs/

**Comment by chenlica** [comment]
Sorry for not giving a comment earlier.  Can we add "BS Thesis" before Shengjie's name?

**Pull request merged**
