### PR TITLE
Add configuration for optional HTTPS & WSS

### LINKED ISSUE #800: TODO - Apply optimizations from CoronavirusTwitterMap to TwitterMap
- [x] (T1) Binary data transfer for Pinmap and Heatmap queries. #780 #784 
- [x] (T2) Update Noah module to use extended twitter API to include `full_text`. #801 
- [x] (T3) TwitterMap server side cache module. #783 #791 
- [x] (T4) WS/WSS configurable. #753 #778

### PR DESCRIPTION
**Pull request by Yicong-Huang**
This PR is referred to #753 (HTTPS config) and #778 (wss config).

### CODE REVIEW

**Comment by Yicong-Huang** [comment]
@baiqiushi can we merge this PR?

**Review by baiqiushi — APPROVED** [review]
LGTM.

**Review by baiqiushi — APPROVED** [review]
LGTM.

**Comment by baiqiushi** [comment]
> @baiqiushi can we merge this PR?

Please go ahead.

**Comment by Yicong-Huang** [comment]
@baiqiushi could you please help check why [codecov report](https://github.com/ISG-ICS/cloudberry/pull/820#issuecomment-4160750895) was triggered recently?

**Pull request merged**
